name: Моя Новая Ручная Задача

# Этот блок отвечает за то, чтобы запускать задачу ТОЛЬКО вручную
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-my-task:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код вашего репозитория на сервер GitHub
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Устанавливаем зависимости (если они нужны, раскомментируйте строку ниже)
      # - run: pip install -r requirements.txt

      # 4. Запускаем ваш другой скрипт
      # ЗАМЕНИТЕ 'other_script.py' на имя файла, который вы хотите запустить
      - name: Run canlitv_source script
        run: python canlitv_source.py
